# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HPzCtJYOpXDvg7-8Ur8AX01f8aRXOI9U

**Завдання 1**
"""

inreger1=8
floating1=4.555
boolean1=True
string1="Flawed"
inreger2=56
integer3=7680000
boolean2=False
string2="Hall"
string3="fgh648340r9023893hdjfb"
floating2=6.9

"""**Завдання 2**"""

a=1
b=2
a,b=b,a
print(a, b)

"""**Завдання 3**"""

x=3
y=9
print(2*x+3*y)
print(x**2+a*x*y+y**2)
print(2/8*x-13/7*y)
print(y**((4*x-2*y)**(1/2)))
print(x%y)
print((y/x)**2)
print(x>y)
print(x**2!=y)

"""**Завдання 4**"""

product_name="Laptop"
product_price=40000
print(f"{product_name} дорівнює {product_price} гривень")

"""**Завдання 5**"""

x1=69
x2=39
x3=216
x4=90
print(x1>x3 or x2>x4 and not x2!=x3 or x1==x4)

"""**Завдання 6**"""

height=float(input("Input your height in m: "))
weight=int(input("Input your weight in kg: "))
bmi=weight/height**2
print(f"If you weight {weight} kg and your height is {height} m your BMI will be {bmi}")

radius1=30
radius2=36.3
s1=radius1**2 * 3.14
s2=radius2**2 * 3.14
diff=(s2-s1)*100/s1
print(f"Друга піца на {diff:,.2f}% більша за першу.")